[Greeter]
background=/usr/share/backgrounds/delinuxco/delinuxco_praia_da_adraga.svg
theme-name=Mint-L-Dark-Grey
icon-theme-name=Mint-L-Brown
cursor-theme-name=Bibata-Modern-Classic
activate-numlock=true
content-align=center
