displaymanager="lightdm"

nonfree_mhwd="true"

enable_systemd=('avahi-daemon' 'avahi-dnsconfd.service' 'bluetooth' 'cronie' 'NetworkManager' 'haveged' 'cups' 'cups-browsed' 'tlp' 'ufw' 'apparmor' 'touchegg' 'systemd-timesyncd' 'manjaro-post-install')
enable_systemd_timers=('fstrim' 'pacman-filesdb-refresh')
disable_systemd_live=('tlp' 'tlp-sleep')

disable_systemd=('pacman-init')

hostname="DeLinuxCo"
